<?php

namespace RequeteBundle\Repository;

use Actarus\Utils;


/**
 * RequeteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequeteRepository extends \Doctrine\ORM\EntityRepository
{
	public function search( $data )
	{
		$t_params = array();
		$qb = $this->_em->createQueryBuilder();
		$query = $qb->select(array('r'))->from('RequeteBundle:Requete','r');
		
		if( $data )
		{
			if ($data->getId()) {
				$query->andWhere('r.id=:id');
				$t_params['id'] = $data->getId();
			}
			if ($data->getProjectId()) {
				$query->andWhere('r.project=:project_id');
				$t_params['project_id'] = $data->getProjectId();
			}
			if ($data->getUrl()) {
				$query->andWhere('r.url LIKE :url OR r.host LIKE :url OR r.path LIKE :url OR r.query LIKE :url');
				$t_params['url'] = '%' . $data->getUrl() . '%';
			}
			if ($data->getMethod()) {
				$query->andWhere('r.method=:method');
				$t_params['method'] = $data->getMethod();
			}
			if ($data->getData()) {
				$query->andWhere('r.data LIKE :data');
				$t_params['data'] = '%' . $data->getData() . '%';
			}
			if ($data->getHeader()) {
				$query->andWhere('r.header LIKE :header');
				$t_params['header'] = '%' . $data->getHeader() . '%';
			}
			if ($data->getCookie()) {
				$query->andWhere('r.cookie LIKE :cookie');
				$t_params['cookie'] = '%' . $data->getCookie() . '%';
			}
			if ($data->getMinCreatedAt()) {
				$query->andWhere('r.createdAt >= :min_created_date');
				$t_params['min_created_date'] = date( 'Y-m-d 00:00:00', Utils::dateFR2Time($data->getMinCreatedAt()) );
			}
			if ($data->getMaxCreatedAt()) {
				$query->andWhere('r.createdAt <= :max_created_date');
				$t_params['max_created_date'] = date( 'Y-m-d 23:59:59', Utils::dateFR2Time($data->getMaxCreatedAt()) );
			}
		}
		
		$query->setParameters( $t_params );
		$query->orderBy('r.id', 'DESC');
		
		$t_result = $query->getQuery()->getResult();
		
		return $t_result;
	}
}
