<?php

namespace ArusEntityTaskBundle\Repository;

use Actarus\Utils;


/**
 * ArusEntityTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArusEntityTaskRepository extends \Doctrine\ORM\EntityRepository
{
	public function search( $data, $offset=null, $limit=null )
	{
		$data = Utils::array2object( $data, 'ArusEntityTaskBundle\Entity\Search' );
		$t_params = array();
		$qb = $this->_em->createQueryBuilder();

		if( $offset < 0 ) {
			$offset = null;
			$count  = true;
			$query  = $qb->select( 'count(et.id)' );
		} else {
			$count  = false;
			$query  = $qb->select( array('et') );
		}
		$query = $query->from('ArusEntityTaskBundle:ArusEntityTask','et');

		if( $data )
		{
			if( ($id=$data->getId()) ) {
				if( !is_array($id) ) {
					$id = [ $id, '=' ];
				}
				$query->andWhere( 'et.id '.$id[1].' :id' );
				$t_params['id'] = $id[0];
			}
			if ($data->getProject()) {
				$query->andWhere('et.project=:project_id');
				$t_params['project_id'] = $data->getProject()->getId();
			}
			if ($data->getEntityType()) {
				$query->andWhere('et.entityId LIKE :entity_type');
				$t_params['entity_type'] = $data->getEntityType().'%';
			}
			if ($data->getEntityId()) {
				$query->andWhere('et.entityId LIKE :entity_id');
				$t_params['entity_id'] = $data->getEntityId();
			}
			if ($data->getCommand()) {
				$query->andWhere('et.command LIKE :command');
				$t_params['command'] = '%'.$data->getCommand().'%';
			}
			if ($data->getOutput()) {
				$query->andWhere('et.output LIKE :output');
				$t_params['output'] = '%'.$data->getOutput().'%';
			}
			if ( !is_null($data->getStatus()) ) {
				$status = $data->getStatus();
				if( !is_array($status) ) {
					$status = [ $status, '=' ];
				}
				$query->andWhere('et.status '.$status[1].' :status');
				$t_params['status'] = $status[0];
			}
			if ($data->getClusterId()) {
				$query->andWhere('et.clusterId LIKE :cluster_id');
				$t_params['cluster_id'] = $data->getClusterId();
			}
			if ($data->getMinCreatedAt()) {
				$query->andWhere('et.createdAt >= :min_created_date');
				$t_params['min_created_date'] = date( 'Y-m-d 00:00:00', Utils::dateFR2Time($data->getMinCreatedAt()) );
			}
			if ($data->getMaxCreatedAt()) {
				$query->andWhere('et.createdAt <= :max_created_date');
				$t_params['max_created_date'] = date( 'Y-m-d 23:59:59', Utils::dateFR2Time($data->getMaxCreatedAt()) );
			}
		}

		$query->setParameters( $t_params );
		//$query->addOrderBy('et.endedAt', 'DESC');
		$query->addOrderBy('et.id', 'DESC');
		if( !is_null($limit) ) {
			$query->setMaxResults( $limit );
		}
		if( !is_null($offset) ) {
			$query->setFirstResult($offset);
		}

		$t_result = $query->getQuery()->getResult();

		if( $count ) {
			return (int)$t_result[0][1];
		} else {
			return $t_result;
		}
	}


	public function getRelatedEntity( $task, $t_entity_type )
	{
		$type = substr( $task->getEntityId(), 0, 1 );
		$entity = 'Arus'.ucfirst($t_entity_type[$type]);
		$related = $this->_em->getRepository($entity.'Bundle:'.$entity)->findOneByEntityId( $task->getEntityId() );

		return $related;
	}


	public function deleteEntity( $entity )
	{
		$qb = $this->createQueryBuilder( 'et' );
		$isDeleted = $qb->delete()->where( 'et.entityId LIKE :entity_id' )->setParameter( 'entity_id',$entity->getEntityId() )->getQuery()->execute();
		return $isDeleted;
	}
}
