<?php

namespace ArusEntityAttachmentBundle\Repository;

use Actarus\Utils;


/**
 * ArusEntityAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArusEntityAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
	public function search( $data, $offset=null, $limit=null )
	{
		$data = Utils::array2object( $data, 'ArusEntityAttachmentBundle\Entity\Search' );
		$t_params = array();
		//var_dump($data);
		$qb = $this->_em->createQueryBuilder();

		if( $offset < 0 ) {
			$offset = null;
			$count  = true;
			$query  = $qb->select( 'count(ea.id)' );
		} else {
			$count  = false;
			$query  = $qb->select( array('ea') );
		}
		$query = $query->from('ArusEntityAttachmentBundle:ArusEntityAttachment','ea');

		if( $data )
		{
			if( ($id=$data->getId()) ) {
				if( !is_array($id) ) {
					$id = [ $id, '=' ];
				}
				$query->andWhere( 'ea.id '.$id[1].' :id' );
				$t_params['id'] = $id[0];
			}
			if ($data->getProject()) {
				$query->andWhere('ea.project=:project_id');
				$t_params['project_id'] = $data->getProject()->getId();
			}
			if ($data->getEntityType()) {
				$query->andWhere('ea.entityId LIKE :entity_type');
				$t_params['entity_type'] = $data->getEntityType().'%';
			}
			if ($data->getEntityId()) {
				$query->andWhere('ea.entityId LIKE :entity_id');
				$t_params['entity_id'] = $data->getEntityId();
			}
			if ($data->getTitle()) {
				$query->andWhere('ea.title LIKE :title');
				$t_params['title'] = '%'.$data->getTitle().'%';
			}
			if ($data->getFilename()) {
				$query->andWhere('ea.filename LIKE :filename');
				$t_params['filename'] = '%'.$data->getFilename().'%';
			}
			if ($data->getRealname()) {
				$query->andWhere('ea.realname LIKE :realname');
				$t_params['realname'] = '%'.$data->getRealname().'%';
			}
			if ($data->getMinCreatedAt()) {
				$query->andWhere('ea.createdAt >= :min_created_date');
				$t_params['min_created_date'] = date( 'Y-m-d 00:00:00', Utils::dateFR2Time($data->getMinCreatedAt()) );
			}
			if ($data->getMaxCreatedAt()) {
				$query->andWhere('ea.createdAt <= :max_created_date');
				$t_params['max_created_date'] = date( 'Y-m-d 23:59:59', Utils::dateFR2Time($data->getMaxCreatedAt()) );
			}
		}

		$query->setParameters( $t_params );
		$query->orderBy('ea.id', 'DESC');
		if( !is_null($limit) ) {
			$query->setMaxResults( $limit );
		}
		if( !is_null($offset) ) {
			$query->setFirstResult($offset);
		}

		$t_result = $query->getQuery()->getResult();

		if( $count ) {
			return (int)$t_result[0][1];
		} else {
			return $t_result;
		}
	}


	public function getRelatedEntity( $attachment, $t_entity_type )
	{
		$type = substr( $attachment->getEntityId(), 0, 1 );
		$entity = 'Arus'.ucfirst($t_entity_type[$type]);
		$related = $this->_em->getRepository($entity.'Bundle:'.$entity)->findOneByEntityId( $attachment->getEntityId() );

		return $related;
	}


	public function deleteEntity( $entity )
	{
		$qb = $this->createQueryBuilder( 'ea' );
		$isDeleted = $qb->delete()->where( 'ea.entityId LIKE :entity_id' )->setParameter( 'entity_id',$entity->getEntityId() )->getQuery()->execute();
		return $isDeleted;
	}
}
