<?php

namespace ArusRequestBundle\Repository;

use Actarus\Utils;


/**
 * ArusRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArusRequestRepository extends \Doctrine\ORM\EntityRepository
{
	public function search( $data, $offset=null, $limit=null )
	{
		$data = Utils::array2object( $data, 'ArusRequestBundle\Entity\Search' );
		$t_params = array();
		$qb = $this->_em->createQueryBuilder();

		if( $offset < 0 ) {
			$offset = null;
			$count  = true;
			$query  = $qb->select( 'count(r.id)' );
		} else {
			$count  = false;
			$query  = $qb->select( array('r') );
		}
		$query = $query->from('ArusRequestBundle:ArusRequest','r');

		if( $data )
		{
			if( ($id=$data->getId()) ) {
				if( !is_array($id) ) {
					$id = [ $id, '=' ];
				}
				$query->andWhere( 'r.id '.$id[1].' :id' );
				$t_params['id'] = $id[0];
			}
			if( ($sign=$data->getSign()) ) {
				if( !is_array($sign) ) {
					$sign = [ '%'.$sign.'%', 'LIKE' ];
				}
				$query->andWhere('r.sign '.$sign[1].' :name');
				$t_params['name'] = $sign[0];
			}
			if ($data->getProject()) {
				$query->andWhere('r.project=:project_id');
				$t_params['project_id'] = $data->getProject()->getId();
			}
			if ($data->getUrl()) {
				$query->andWhere('r.url LIKE :url OR r.host LIKE :url OR r.path LIKE :url OR r.query LIKE :url');
				$t_params['url'] = '%' . $data->getUrl() . '%';
			}
			if ($data->getMethod()) {
				$query->andWhere('r.method=:method');
				$t_params['method'] = $data->getMethod();
			}
			if ($data->getData()) {
				$query->andWhere('r.data LIKE :data');
				$t_params['data'] = '%' . $data->getData() . '%';
			}
			if ($data->getHeader()) {
				$query->andWhere('r.header LIKE :header');
				$t_params['header'] = '%' . $data->getHeader() . '%';
			}
			if ($data->getCookie()) {
				$query->andWhere('r.cookie LIKE :cookie');
				$t_params['cookie'] = '%' . $data->getCookie() . '%';
			}
			if ($data->getMinCreatedAt()) {
				$query->andWhere('r.createdAt >= :min_created_date');
				$t_params['min_created_date'] = date( 'Y-m-d 00:00:00', Utils::dateFR2Time($data->getMinCreatedAt()) );
			}
			if ($data->getMaxCreatedAt()) {
				$query->andWhere('r.createdAt <= :max_created_date');
				$t_params['max_created_date'] = date( 'Y-m-d 23:59:59', Utils::dateFR2Time($data->getMaxCreatedAt()) );
			}
		}
		
		$query->setParameters( $t_params );
		$query->orderBy('r.id', 'DESC');
		if( !is_null($limit) ) {
			$query->setMaxResults( $limit );
		}
		if( !is_null($offset) ) {
			$query->setFirstResult($offset);
		}

		$t_result = $query->getQuery()->getResult();

		if( $count ) {
			return (int)$t_result[0][1];
		} else {
			return $t_result;
		}
	}
}
