<?php

namespace ArusTaskBundle\Repository;

use Doctrine\Common\Util\Inflector as Inflector;


/**
 * ArusTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArusTaskRepository extends \Doctrine\ORM\EntityRepository
{
	public function findArray( $key='id', $value=['name','command'] )
	{
		if( !is_array($value) ) {
			$value = [$value];
		}
		
		$tab = array();
		$r = $this->findAll();
		
		foreach( $r as $o ) {
			$fk = Inflector::camelize('get_'.$key);
			$tmp = [];
			foreach( $value as $v ) {
				$fv = Inflector::camelize('get_'.$v);
				$tmp[$v] = $o->$fv();
			}
			if( count($tmp) == 1 ) {
				$tmp = array_pop( $tmp );
			}
			$tab[ $o->$fk() ] = $tmp;
			//$tab[ $o->getId() ] = $o->getName();
			//$tab[ $fk ] = array( 'name'=>$o->getName(), 'command'=>$o->getCommand() );
		}
		
		return $tab;
	}
	
	
	public function findAll()
	{
		$qb = $this->createQueryBuilder('t');
		$query = $qb->select(array('t'))->orderBy('t.name', 'ASC');
		$t_result = $query->getQuery()->getResult();
		
		return $t_result;
	}
}
