<?php

namespace ArusHostServerBundle\Repository;

/**
 * ArusHostServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArusHostServerRepository extends \Doctrine\ORM\EntityRepository
{
}
